"""add missing tables: scan_fields, index_exclusions

Revision ID: 13694664e7a5
Revises: cf1b3474db3e
Create Date: 2026-08-24 22:55:57.102433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13694664e7a5'
down_revision: Union[str, Sequence[str], None] = 'cf1b3474db3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_field_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_pattern', sa.String(), nullable=False, default='*'),
    sa.Column('field_path', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), default=True, nullable=False),
    sa.Column('is_required', sa.Boolean(), default=False, nullable=False),
    sa.Column('created_at', sa.DateTime(), default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_field_configs_id'), 'scan_field_configs', ['id'], unique=False)
    
    op.create_table('index_key_exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_pattern', sa.String(), nullable=False),
    sa.Column('pdn_type', sa.String(), nullable=False),
    sa.Column('key_path', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), default=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_key_exclusions_id'), 'index_key_exclusions', ['id'], unique=False)
    op.create_index(op.f('ix_index_key_exclusions_index_pattern'), 'index_key_exclusions', ['index_pattern'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_index_key_exclusions_index_pattern'), table_name='index_key_exclusions')
    op.drop_index(op.f('ix_index_key_exclusions_id'), table_name='index_key_exclusions')
    op.drop_table('index_key_exclusions')
    op.drop_index(op.f('ix_scan_field_configs_id'), table_name='scan_field_configs')
    op.drop_table('scan_field_configs')
    # ### end Alembic commands ###
