"""Initial_migration

Revision ID: 7ee6282b4ef6
Revises: 
Create Date: 2026-03-01 23:37:15.079419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ee6282b4ef6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correction_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_issue_key', sa.String(), nullable=False),
    sa.Column('index_pattern', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_tasks_id'), 'correction_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_correction_tasks_index_pattern'), 'correction_tasks', ['index_pattern'], unique=False)
    op.create_index(op.f('ix_correction_tasks_jira_issue_key'), 'correction_tasks', ['jira_issue_key'], unique=True)
    op.create_table('index_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_pattern', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('contact_person', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('jira_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_owners_id'), 'index_owners', ['id'], unique=False)
    op.create_index(op.f('ix_index_owners_index_pattern'), 'index_owners', ['index_pattern'], unique=True)
    op.create_table('pdn_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('index_pattern', sa.String(), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=False),
    sa.Column('field_path', sa.String(), nullable=False),
    sa.Column('prefix_raw', sa.String(), nullable=True),
    sa.Column('suffix_raw', sa.String(), nullable=True),
    sa.Column('full_document', sa.JSON(), nullable=True),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pdn_findings_cache_key'), 'pdn_findings', ['cache_key'], unique=False)
    op.create_index(op.f('ix_pdn_findings_id'), 'pdn_findings', ['id'], unique=False)
    op.create_table('pdn_patterns',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('index_pattern', sa.String(), nullable=False),
    sa.Column('field_path', sa.String(), nullable=False),
    sa.Column('pdn_type', sa.String(), nullable=False),
    sa.Column('context_type', sa.String(), nullable=False),
    sa.Column('key_hint', sa.String(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('false_positive_comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_pdn_patterns_cache_key'), 'pdn_patterns', ['cache_key'], unique=False)
    op.create_index(op.f('ix_pdn_patterns_index_pattern'), 'pdn_patterns', ['index_pattern'], unique=False)
    op.create_table('regex_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdn_type', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regex_rules_id'), 'regex_rules', ['id'], unique=False)
    op.create_index(op.f('ix_regex_rules_pdn_type'), 'regex_rules', ['pdn_type'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_table('pattern_tags',
    sa.Column('pattern_cache_key', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pattern_cache_key'], ['pdn_patterns.cache_key'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('pattern_cache_key', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pattern_tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_regex_rules_pdn_type'), table_name='regex_rules')
    op.drop_index(op.f('ix_regex_rules_id'), table_name='regex_rules')
    op.drop_table('regex_rules')
    op.drop_index(op.f('ix_pdn_patterns_index_pattern'), table_name='pdn_patterns')
    op.drop_index(op.f('ix_pdn_patterns_cache_key'), table_name='pdn_patterns')
    op.drop_table('pdn_patterns')
    op.drop_index(op.f('ix_pdn_findings_id'), table_name='pdn_findings')
    op.drop_index(op.f('ix_pdn_findings_cache_key'), table_name='pdn_findings')
    op.drop_table('pdn_findings')
    op.drop_index(op.f('ix_index_owners_index_pattern'), table_name='index_owners')
    op.drop_index(op.f('ix_index_owners_id'), table_name='index_owners')
    op.drop_table('index_owners')
    op.drop_index(op.f('ix_correction_tasks_jira_issue_key'), table_name='correction_tasks')
    op.drop_index(op.f('ix_correction_tasks_index_pattern'), table_name='correction_tasks')
    op.drop_index(op.f('ix_correction_tasks_id'), table_name='correction_tasks')
    op.drop_table('correction_tasks')
    # ### end Alembic commands ###
