"""add_custom_message_to_pdn_pattern

Revision ID: 914484850430
Revises: 7ee6282b4ef6
Create Date: 2026-03-02 22:59:04.124753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '914484850430'
down_revision: Union[str, Sequence[str], None] = '7ee6282b4ef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_issue_key', sa.String(), nullable=False),
    sa.Column('index_pattern', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jira_tasks_id'), 'jira_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_jira_tasks_index_pattern'), 'jira_tasks', ['index_pattern'], unique=False)
    op.create_index(op.f('ix_jira_tasks_jira_issue_key'), 'jira_tasks', ['jira_issue_key'], unique=True)
    op.create_table('scanner_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_type', sa.String(), nullable=False),
    sa.Column('target_index', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('findings_count', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanner_logs_id'), 'scanner_logs', ['id'], unique=False)
    op.create_table('status_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_settings_id'), 'status_settings', ['id'], unique=False)
    op.drop_index(op.f('ix_correction_tasks_id'), table_name='correction_tasks')
    op.drop_index(op.f('ix_correction_tasks_index_pattern'), table_name='correction_tasks')
    op.drop_index(op.f('ix_correction_tasks_jira_issue_key'), table_name='correction_tasks')
    op.drop_table('correction_tasks')
    op.add_column('index_owners', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('index_owners', sa.Column('override_global_settings', sa.Boolean(), nullable=True))
    op.add_column('pdn_patterns', sa.Column('custom_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdn_patterns', 'custom_message')
    op.drop_column('index_owners', 'override_global_settings')
    op.drop_column('index_owners', 'is_active')
    op.create_table('correction_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jira_issue_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('index_pattern', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('assignee', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('correction_tasks_pkey'))
    )
    op.create_index(op.f('ix_correction_tasks_jira_issue_key'), 'correction_tasks', ['jira_issue_key'], unique=True)
    op.create_index(op.f('ix_correction_tasks_index_pattern'), 'correction_tasks', ['index_pattern'], unique=False)
    op.create_index(op.f('ix_correction_tasks_id'), 'correction_tasks', ['id'], unique=False)
    op.drop_index(op.f('ix_status_settings_id'), table_name='status_settings')
    op.drop_table('status_settings')
    op.drop_index(op.f('ix_scanner_logs_id'), table_name='scanner_logs')
    op.drop_table('scanner_logs')
    op.drop_index(op.f('ix_jira_tasks_jira_issue_key'), table_name='jira_tasks')
    op.drop_index(op.f('ix_jira_tasks_index_pattern'), table_name='jira_tasks')
    op.drop_index(op.f('ix_jira_tasks_id'), table_name='jira_tasks')
    op.drop_table('jira_tasks')
    # ### end Alembic commands ###
