"""update index_owners table fields

Revision ID: 9628d80a6040
Revises: 9f2c1b3bf858
Create Date: 2026-03-10 22:42:54.857468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9628d80a6040'
down_revision: Union[str, Sequence[str], None] = '9f2c1b3bf858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_key_exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index_pattern', sa.String(), nullable=False),
    sa.Column('pdn_type', sa.String(), nullable=False),
    sa.Column('key_path', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_key_exclusions_id'), 'index_key_exclusions', ['id'], unique=False)
    op.create_index(op.f('ix_index_key_exclusions_index_pattern'), 'index_key_exclusions', ['index_pattern'], unique=False)
    op.add_column('index_owners', sa.Column('cmdb_url', sa.String(), nullable=True))
    op.add_column('index_owners', sa.Column('tech_debt_id', sa.String(), nullable=True))
    op.add_column('index_owners', sa.Column('fio', sa.String(), nullable=True))
    op.drop_column('index_owners', 'contact_person')
    op.drop_column('index_owners', 'contact_email')
    op.drop_column('index_owners', 'jira_key')
    op.drop_column('index_owners', 'notes')
    op.drop_column('index_owners', 'override_global_settings')
    op.drop_column('index_owners', 'team_name')
    op.drop_column('index_owners', 'is_active')
    op.add_column('pdn_patterns', sa.Column('extra_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdn_patterns', 'extra_fields')
    op.add_column('index_owners', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('index_owners', sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('index_owners', sa.Column('override_global_settings', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('index_owners', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('index_owners', sa.Column('jira_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('index_owners', sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('index_owners', sa.Column('contact_person', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('index_owners', 'fio')
    op.drop_column('index_owners', 'tech_debt_id')
    op.drop_column('index_owners', 'cmdb_url')
    op.drop_index(op.f('ix_index_key_exclusions_index_pattern'), table_name='index_key_exclusions')
    op.drop_index(op.f('ix_index_key_exclusions_id'), table_name='index_key_exclusions')
    op.drop_table('index_key_exclusions')
    # ### end Alembic commands ###
