"""add_jira_task_history_fields

Revision ID: 9f2c1b3bf858
Revises: 914484850430
Create Date: 2026-03-02 23:29:15.363271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2c1b3bf858'
down_revision: Union[str, Sequence[str], None] = '914484850430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_tasks', sa.Column('author_name', sa.String(), nullable=True))
    op.add_column('jira_tasks', sa.Column('jira_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jira_tasks', 'jira_url')
    op.drop_column('jira_tasks', 'author_name')
    # ### end Alembic commands ###
